---
- name: Install Docker Compose
  become: yes
  apt:
    name: docker-compose
    state: present

- name: Copy Docker Compose file for ELK stack
  copy:
    src: roles/install_elk_stack/files/docker-compose.yml
    dest: /opt/docker-compose.yml

- name: Start ELK stack containers
  docker_compose:
    project_src: /opt/docker-compose.yml
    state: present
  become: yes

